version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
  - dependency-name: postcss
    versions:
    - 8.2.4
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
  - dependency-name: rollup-plugin-license
    versions:
    - 2.2.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
